version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - containedctx
    - contextcheck
    - cyclop
    - dupword
    - err113
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - maintidx
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - nonamedreturns
    - predeclared
    - recvcheck
    - tagliatelle
    - testifylint
    - usetesting
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
            - '!$test'
          allow:
            - $gostd
            - github.com/cockroachdb/pebble
            - github.com/google/btree
            - github.com/syndtr/goleveldb/leveldb
        test:
          files:
            - $test
          allow:
            - $gostd
            - github.com/stretchr/testify
            - github.com/syndtr/goleveldb/leveldb/opt
    dogsled:
      max-blank-identifiers: 3
    gosec:
      excludes:
        - G115
    misspell:
      locale: US
    revive:
      enable-all-rules: true
      rules:
        - name: comment-spacings
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: cognitive-complexity
          disabled: true
        - name: argument-limit
          disabled: true
        - name: cyclomatic
          disabled: true
        - name: deep-exit
          disabled: true
        - name: file-header
          disabled: true
        - name: function-length
          disabled: true
        - name: function-result-limit
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: add-constant
          disabled: true
        - name: empty-lines
          disabled: true
        - name: import-shadowing
          disabled: true
        - name: modifies-value-receiver
          disabled: true
        - name: confusing-naming
          disabled: true
        - name: defer
          disabled: true
        - name: unchecked-type-assertion
          disabled: true
        - name: unhandled-error
          arguments:
            - fmt.Printf
            - fmt.Print
            - fmt.Println
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gocritic
          - goimport
          - gosec
          - noctx
          - paralleltest
          - testpackage
          - tparallel
        path: _test\.go
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 10000
  max-same-issues: 10000
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(github.com/cometbft/cometbft-db)
      custom-order: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - _test\.go
