name: Test fast (no changes to Dockerfile)

on:
  pull_request:
    paths-ignore:
      - "tools/**"
  merge_group:
  push:
    branches:
      - main
    paths-ignore:
      - "tools/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-fast:
    runs-on: ubuntu-latest
    container: cometbft/cometbft-db-testing
    steps:
      - uses: actions/checkout@v4

      - run: echo "GO_VERSION=$(cat .github/workflows/go-version.env | grep GO_VERSION | cut -d '=' -f2)" >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: test & coverage report creation
        run: |
          NON_INTERACTIVE=1 make test-all-with-coverage

      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
