name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  ORG: cometbft
  IMAGE_NAME: cometbft-db-testing

jobs:
  golangci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and load
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          file: ./tools/Dockerfile
          tags: "${{ env.ORG }}/${{ env.IMAGE_NAME }}:latest"
          load: true

      - uses: golangci/golangci-lint-action@v6.1.0
        with:
          args: --timeout 10m
          version: latest
          github-token: ${{ secrets.github_token }}
      - name: lint
        run: |
          NON_INTERACTIVE=1 make docker-lint
