name: Test
on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  ORG: cometbft
  IMAGE_NAME: cometbft-db-testing

jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and load
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ matrix.platform }}
          file: ./tools/Dockerfile
          tags: "${{ env.ORG }}/${{ env.IMAGE_NAME }}:latest"
          load: true

      - name: test & coverage report creation
        run: |
          NON_INTERACTIVE=1 make docker-test

      - uses: codecov/codecov-action@v4
        with:
          file: ./coverage.txt
